# Generated by Django 3.0.2 on 2020-02-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20200221_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiletable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='pqr', max_length=264)),
                ('ingredients', models.CharField(default='pqr', max_length=264)),
                ('time', models.CharField(default='pqr', max_length=264)),
                ('directions', models.CharField(default='pqr', max_length=264)),
                ('description', models.CharField(default='pqr', max_length=264)),
                ('image', models.FileField(default='firstpro/static/pallav_resume.pdf', upload_to='fileupload')),
            ],
        ),
    ]
