# Generated by Django 3.0.2 on 2020-02-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_profiletable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletable',
            old_name='description',
            new_name='de',
        ),
        migrations.RenameField(
            model_name='profiletable',
            old_name='directions',
            new_name='di',
        ),
        migrations.RenameField(
            model_name='profiletable',
            old_name='image',
            new_name='im',
        ),
        migrations.RenameField(
            model_name='profiletable',
            old_name='ingredients',
            new_name='ing',
        ),
        migrations.RenameField(
            model_name='profiletable',
            old_name='name',
            new_name='na',
        ),
        migrations.RenameField(
            model_name='profiletable',
            old_name='time',
            new_name='ti',
        ),
    ]
