# Generated by Django 3.0.2 on 2020-02-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_profiletable_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltable',
            name='image',
            field=models.FileField(default='firstpro/static/p_resume.pdf', upload_to='fileupload'),
        ),
        migrations.AlterField(
            model_name='profiletable',
            name='im',
            field=models.FileField(default='firstpro/static/p_resume.pdf', upload_to='fileupload'),
        ),
    ]
