# Generated by Django 3.0.2 on 2020-02-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20200221_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profiletable',
        ),
        migrations.AlterField(
            model_name='modeltable',
            name='image',
            field=models.FileField(default='firstpro/static/def.jpg', upload_to='fileupload'),
        ),
    ]
