# Generated by Django 3.0.2 on 2020-02-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20200223_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltable',
            name='name',
            field=models.CharField(max_length=264),
        ),
    ]
