# Generated by Django 3.0.2 on 2020-02-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20200223_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltable',
            name='description',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='modeltable',
            name='directions',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='modeltable',
            name='image',
            field=models.FileField(upload_to='fileupload'),
        ),
        migrations.AlterField(
            model_name='modeltable',
            name='ingredients',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='modeltable',
            name='time',
            field=models.CharField(max_length=264),
        ),
    ]
